name: Test Font

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Noto Color Emoji font
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-color-emoji
          fc-list | grep "Noto Color Emoji"
          echo "🧠 🐳 Impressions"

